services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    user: root
    ports:
      - "127.0.0.1:8001:8000"
    volumes:
      - ecommerce-data:/data
  seed:
    build: .
    depends_on:
      - dynamodb
    environment:
      DYNAMODB_ENDPOINT_URL: http://dynamodb:8000
    restart: "no"
volumes:
  ecommerce-data:
